# Generated by Django 5.1.4 on 2025-08-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='expectation',
            field=models.TextField(blank=True, help_text='What do you hope to gain from this event?', null=True),
        ),
    ]
