# Generated by Django 5.1.4 on 2025-08-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registration_expectation'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Pastor', 'Pastor'), ('Rev', 'Rev')], default='Mr', max_length=10),
        ),
    ]
