# Generated by Django 5.1.4 on 2025-08-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_registration_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='expectation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
